@startuml
actor Business
participant TransactionExecutor
participant SpringTM as PlatformTransactionManager
participant DB as Database

Business -> TransactionExecutor: REQUIRED
TransactionExecutor -> SpringTM: getTransaction(REQUIRED)
SpringTM --> TransactionExecutor: Tx-A
TransactionExecutor -> DB: INSERT outer (Tx-A)

Business -> TransactionExecutor: REQUIRES_NEW
TransactionExecutor -> SpringTM: getTransaction(REQUIRES_NEW)
note right of SpringTM
  suspend Tx-A
  create Tx-B
end note
SpringTM --> TransactionExecutor: Tx-B
TransactionExecutor -> DB: INSERT inner (Tx-B)
TransactionExecutor -> SpringTM: commit(Tx-B)
note right of SpringTM
  commit Tx-B
  resume Tx-A
end note

Business --> TransactionExecutor: throw exception in outer
TransactionExecutor -> SpringTM: rollback(Tx-A)
@enduml
