spring:
  application:
    name: observability-demo-app

xy:
  observability:
    enabled: true
    instrumentation-name: observability-demo-app
    trace-aspect-enabled: true
#    web-mdc-enabled: true
#    method-mdc-enabled: true
#    emplate-mdc-enabled: true