CREATE TABLE IF NOT EXISTS iron_idempotency_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 namespace VARCHAR(128) NOT NULL,
 idempotency_key VARCHAR(256) NOT NULL,
 request_hash VARCHAR(128), status VARCHAR(32) NOT NULL, owner_token VARCHAR(128), version BIGINT NOT NULL DEFAULT 0,
 result_payload CLOB, failure_code VARCHAR(128), failure_message VARCHAR(1024), failure_retryable BOOLEAN NOT NULL DEFAULT FALSE,
 processing_expire_at TIMESTAMP, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, completed_at TIMESTAMP,
 CONSTRAINT uk_iron_idempotency_namespace_key UNIQUE(namespace,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_iron_idempotency_status_expire ON iron_idempotency_record(status,processing_expire_at);
