iron:
  distributed-lock:
    enabled: true
    default-provider: redis
    namespace: default
    lease-time: 30s
    wait-time: 0s
    auto-renew: false
    max-renew-time: 10m
    fail-on-lock-lost: true

    redis:
      enabled: true
      key-prefix: iron:lock
      release-channel-prefix: iron:lock:release
      fencing-key-suffix: fence