<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xjtu.iron</groupId>
        <artifactId>component</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>observability-component</artifactId>
    <packaging>pom</packaging>
    <name>observability-parent</name>
    <modules>
        <module>observability-core</module>
        <module>observability-starter</module>
        <module>observability-api</module>
        <module>observability-otel</module>
        <module>observability-demo-app</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.xjtu.iron</groupId>
                <artifactId>component-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
