package com.xjtu.iron.relational.integration.spring;

import com.xjtu.iron.relational.api.RelationalTemplate;
import com.xjtu.iron.relational.api.statement.SqlStatement;
import com.xjtu.iron.relational.core.DefaultRelationalTemplate;
import com.xjtu.iron.relational.core.connection.SingleDataSourceResolver;
import com.xjtu.iron.relational.core.exception.StandardSqlExceptionTranslator;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class SpringTransactionAwareConnectionProviderIntegrationTest {

    private JdbcDataSource dataSource;
    private JdbcTemplate jdbcTemplate;
    private RelationalTemplate relationalTemplate;
    private TransactionTemplate transactionTemplate;

    @BeforeEach
    void setUp() {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:relational_spring_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE tx_test (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    source VARCHAR(32) NOT NULL
                )
                """);

        relationalTemplate = new DefaultRelationalTemplate(
                new SpringTransactionAwareConnectionProvider(new SingleDataSourceResolver(dataSource)),
                new StandardSqlExceptionTranslator()
        );
        transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
    }

    @Test
    void rollbackShouldRollbackJdbcTemplateAndRelationalTemplateTogether() {
        transactionTemplate.executeWithoutResult(status -> {
            jdbcTemplate.update("INSERT INTO tx_test(source) VALUES (?)", "business");
            relationalTemplate.update(SqlStatement.of(
                    "test.relational-insert",
                    "INSERT INTO tx_test(source) VALUES (?)",
                    "relational"
            ));
            status.setRollbackOnly();
        });

        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM tx_test", Integer.class);
        assertThat(count).isZero();
    }

    @Test
    void commitShouldPersistBothAccessPaths() {
        transactionTemplate.executeWithoutResult(status -> {
            jdbcTemplate.update("INSERT INTO tx_test(source) VALUES (?)", "business");
            relationalTemplate.update(SqlStatement.of(
                    "test.relational-insert",
                    "INSERT INTO tx_test(source) VALUES (?)",
                    "relational"
            ));
        });

        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM tx_test", Integer.class);
        assertThat(count).isEqualTo(2);
    }
}
