@startuml

title Distributed Lock Main Sequence

actor BusinessService

box "API Module" #D9EAF7

participant DistributedLockClient
participant LockHandle

end box


box "Core Module" #DFF2BF

participant LockExecutionTemplate
participant LockAcquisitionService
participant FencingTokenCoordinator
participant LockWatchDog

end box


box "Provider Module" #FFE6CC

participant LockProvider
participant RedisLockProvider

end box


box "Business Resource" #EEEEEE

participant Repository
database DB

end box



BusinessService -> DistributedLockClient : execute(lockKey)

DistributedLockClient -> LockExecutionTemplate : execute()

LockExecutionTemplate -> LockAcquisitionService : acquire(lockKey)

LockAcquisitionService -> LockProvider : acquire()

LockProvider -> RedisLockProvider : tryLock()

RedisLockProvider --> LockProvider : lockSuccess

LockProvider --> LockAcquisitionService : LockHandle

LockAcquisitionService --> LockExecutionTemplate : acquired


LockExecutionTemplate -> FencingTokenCoordinator : nextToken()

FencingTokenCoordinator --> LockExecutionTemplate : fencingToken


LockExecutionTemplate -> BusinessService : execute business logic


BusinessService -> Repository : update(data,fencingToken)

Repository -> DB : update with token

DB --> Repository : success


LockExecutionTemplate -> LockWatchDog : startRenew()

LockWatchDog -> RedisLockProvider : renew()


LockExecutionTemplate -> LockProvider : release()

LockProvider -> RedisLockProvider : unlock()

RedisLockProvider --> LockProvider : released


@enduml