-- KEYS[1] hash key
-- ARGV nowMs, owner, requestHash, processingTimeoutMs, recordTtlMs, retryFailed, retryTimeout, namespace, logicalKey
local key=KEYS[1];local now=tonumber(ARGV[1]);local owner=ARGV[2];local reqHash=ARGV[3];local pto=tonumber(ARGV[4]);local ttl=tonumber(ARGV[5]);local retryFailed=ARGV[6]=='1';local retryTimeout=ARGV[7]=='1';local ns=ARGV[8];local logicalKey=ARGV[9]
local function h(n)local v=redis.call('HGET',key,n);if not v then return '' end;return v end
local function snap(code,takeover)return {tostring(code),takeover and '1' or '0',h('namespace'),h('key'),h('request_hash'),h('status'),h('owner_token'),h('version'),h('result_payload'),h('failure_code'),h('failure_message'),h('failure_retryable'),h('processing_expire_at'),h('created_at'),h('updated_at'),h('completed_at')} end
if redis.call('EXISTS',key)==0 then redis.call('HSET',key,'namespace',ns,'key',logicalKey,'request_hash',reqHash,'status','PROCESSING','owner_token',owner,'version','1','result_payload','','failure_code','','failure_message','','failure_retryable','0','processing_expire_at',tostring(now+pto),'created_at',tostring(now),'updated_at',tostring(now),'completed_at','');redis.call('PEXPIRE',key,ttl);return snap(1,false) end
local oldHash=h('request_hash');if oldHash~='' and reqHash~='' and oldHash~=reqHash then return snap(5,false) end
local status=h('status');if status=='SUCCESS' then return snap(2,false) end
if status=='PROCESSING' then local exp=tonumber(h('processing_expire_at')) or 0;if exp>now then return snap(3,false) end;redis.call('HSET',key,'status','FAILED','failure_code','PROCESSING_TIMEOUT','failure_message','processing owner lease expired','failure_retryable','1','processing_expire_at','','updated_at',tostring(now));redis.call('PEXPIRE',key,ttl);if not retryTimeout then return snap(4,false) end;status='FAILED' end
if status=='FAILED' then local timeout=h('failure_code')=='PROCESSING_TIMEOUT';if timeout then if not retryTimeout then return snap(4,false) end else if (not retryFailed) or h('failure_retryable')~='1' then return snap(4,false) end end;local ver=(tonumber(h('version')) or 0)+1;redis.call('HSET',key,'status','PROCESSING','owner_token',owner,'version',tostring(ver),'processing_expire_at',tostring(now+pto),'result_payload','','completed_at','','updated_at',tostring(now));redis.call('PEXPIRE',key,ttl);return snap(1,true) end
return snap(4,false)
