package com.xjtu.iron.idempotent.integration.transaction;

import com.xjtu.iron.idempotent.api.*;
import com.xjtu.iron.idempotent.api.repository.*;
import com.xjtu.iron.idempotent.core.*;
import com.xjtu.iron.idempotent.provider.jdbc.JdbcIdempotencyRepository;
import com.xjtu.iron.transaction.api.execution.TransactionExecutor;
import com.xjtu.iron.transaction.core.executor.DefaultTransactionExecutor;
import com.xjtu.iron.transaction.provider.spring.transaction.SpringTransactionProvider;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

import javax.sql.DataSource;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * V1.2 Tx-A / Tx-B / Tx-C 的端到端验证。
 */
class IdempotencyTransactionIntegrationTest {

    private DataSource dataSource;
    private JdbcTemplate jdbcTemplate;
    private TransactionExecutor transactionExecutor;

    @BeforeEach
    void setUp() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:idem-tx-" + UUID.randomUUID()
                + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        this.dataSource = ds;
        this.jdbcTemplate = new JdbcTemplate(ds);

        jdbcTemplate.execute("""
                CREATE TABLE iron_idempotency_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    namespace VARCHAR(128) NOT NULL,
                    idempotency_key VARCHAR(256) NOT NULL,
                    route_key VARCHAR(256),
                    request_hash VARCHAR(128),
                    status VARCHAR(32) NOT NULL,
                    owner_token VARCHAR(128),
                    version BIGINT NOT NULL DEFAULT 0,
                    result_payload CLOB,
                    failure_code VARCHAR(128),
                    failure_message VARCHAR(1024),
                    failure_retryable BOOLEAN NOT NULL DEFAULT FALSE,
                    recovery_mode VARCHAR(32) NOT NULL DEFAULT 'NONE',
                    window_policy VARCHAR(64) NOT NULL DEFAULT 'FIXED_FROM_FIRST_ACQUIRE',
                    processing_expire_at TIMESTAMP,
                    window_expire_at TIMESTAMP,
                    retention_expire_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    completed_at TIMESTAMP,
                    CONSTRAINT uk_idem UNIQUE(namespace, idempotency_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE business_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    idempotency_key VARCHAR(256) NOT NULL,
                    payload VARCHAR(256) NOT NULL
                )
                """);

        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager(ds);
        this.transactionExecutor = new DefaultTransactionExecutor(
                new SpringTransactionProvider(transactionManager));
    }

    @Test
    void successShouldCommitBusinessAndSuccessInSameTransaction() {
        JdbcIdempotencyRepository repository = jdbcRepository();
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("success-1"),
                String.class,
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "ok");
                    return "done";
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.EXECUTED);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("success-1")).isEqualTo(1);
        assertThat(repository.find("tx-test", "success-1"))
                .get()
                .extracting(IdempotencyRecord::getStatus)
                .isEqualTo(IdempotencyStatus.SUCCESS);
    }

    @Test
    void businessFailureShouldRollbackBusinessThenPersistFailedInNewTransaction() {
        JdbcIdempotencyRepository repository = jdbcRepository();
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("failure-1"),
                String.class,
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "must-rollback");
                    throw new IllegalStateException("boom");
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.EXECUTION_FAILED);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("failure-1")).isZero();
        assertThat(repository.find("tx-test", "failure-1"))
                .get()
                .satisfies(record -> {
                    assertThat(record.getStatus()).isEqualTo(IdempotencyStatus.FAILED);
                    assertThat(record.isFailureRetryable()).isTrue();
                });
    }

    @Test
    void completionRejectedShouldRollbackBusinessWriteInsteadOfCommittingPartialSuccess() {
        JdbcIdempotencyRepository delegate = jdbcRepository();
        IdempotencyRepository repository = new RejectingCompletionRepository(delegate);
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("stale-1"),
                String.class,
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "must-rollback");
                    return "done";
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.OWNERSHIP_LOST);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("stale-1")).isZero();
        assertThat(delegate.find("tx-test", "stale-1"))
                .get()
                .extracting(IdempotencyRecord::getStatus)
                .isEqualTo(IdempotencyStatus.PROCESSING);
    }

    private JdbcIdempotencyRepository jdbcRepository() {
        return new JdbcIdempotencyRepository(
                new SpringTransactionJdbcExecutionManager(dataSource, transactionExecutor),
                "iron_idempotency_record");
    }

    private DefaultIdempotencyExecutor executor(IdempotencyRepository repository) {
        IdempotencyRepositoryRegistry registry = new DefaultIdempotencyRepositoryRegistry(
                List.of(repository), repository.providerName(), repository.providerName());
        IdempotencyOptions defaults = options();

        return new DefaultIdempotencyExecutor(
                registry,
                new IdempotencyDefaults(IdempotencyMode.DURABLE, defaults, defaults),
                (namespace, key) -> UUID.randomUUID().toString(),
                (error, at) -> new IdempotencyFailureInfo(
                        "BUSINESS_ERROR",
                        error.getMessage(),
                        true,
                        at),
                null,
                null,
                new TransactionTemplateIdempotencyTransactionCoordinator(transactionExecutor),
                null,
                null,
                Clock.systemUTC());
    }

    private IdempotencyRequest request(String key) {
        return IdempotencyRequest.builder()
                .key(key)
                .routeKey("merchant-1")
                .requestHash("hash-" + key)
                .options(options())
                .build();
    }

    private IdempotencyOptions options() {
        return IdempotencyOptions.builder()
                .mode(IdempotencyMode.DURABLE)
                .recoveryMode(IdempotencyRecoveryMode.EXTERNAL_TASK)
                .recoverFailed(true)
                .storeResult(false)
                .build();
    }

    private int countBusiness(String key) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM business_record WHERE idempotency_key=?",
                Integer.class,
                key);
        return count == null ? 0 : count;
    }

    /**
     * 模拟 owner/version 已在 callback 期间失效：markSuccess 不能 UPDATED。
     * Core 必须把该状态转成异常，让 Tx-B 中已经执行的业务 SQL 回滚。
     */
    private static final class RejectingCompletionRepository implements IdempotencyRepository {
        private final JdbcIdempotencyRepository delegate;

        private RejectingCompletionRepository(JdbcIdempotencyRepository delegate) {
            this.delegate = delegate;
        }

        @Override
        public String providerName() {
            return "rejecting-jdbc";
        }

        @Override
        public boolean supports(IdempotencyMode mode) {
            return delegate.supports(mode);
        }

        @Override
        public boolean supportsBusinessTransactionParticipation() {
            return true;
        }

        @Override
        public IdempotencyAcquireResult tryAcquire(IdempotencyAcquireRequest request) {
            return delegate.tryAcquire(request);
        }

        @Override
        public IdempotencyRecoveryResult tryRecover(IdempotencyRecoveryAcquireRequest request) {
            return delegate.tryRecover(request);
        }

        @Override
        public IdempotencyWriteResult markSuccess(IdempotencySuccessRequest request) {
            Optional<IdempotencyRecord> current = delegate.find(request.getNamespace(), request.getKey());
            return IdempotencyWriteResult.of(
                    IdempotencyWriteStatus.STALE_OWNER,
                    current.orElse(null));
        }

        @Override
        public IdempotencyWriteResult markFailed(IdempotencyFailureRequest request) {
            return delegate.markFailed(request);
        }

        @Override
        public Optional<IdempotencyRecord> find(String namespace, String key) {
            return delegate.find(namespace, key);
        }
    }
}
