package com.xjtu.iron.idempotent.integration.transaction;

import com.xjtu.iron.idempotent.api.execution.*;
import com.xjtu.iron.idempotent.api.policy.*;
import com.xjtu.iron.idempotent.api.recovery.*;
import com.xjtu.iron.idempotent.api.state.*;
import com.xjtu.iron.idempotent.api.repository.*;
import com.xjtu.iron.idempotent.api.repository.acquire.*;
import com.xjtu.iron.idempotent.api.repository.recovery.*;
import com.xjtu.iron.idempotent.api.repository.write.*;
import com.xjtu.iron.idempotent.core.execution.*;
import com.xjtu.iron.idempotent.core.failure.*;
import com.xjtu.iron.idempotent.core.owner.*;
import com.xjtu.iron.idempotent.core.policy.*;
import com.xjtu.iron.idempotent.core.recovery.*;
import com.xjtu.iron.idempotent.core.repository.*;
import com.xjtu.iron.idempotent.core.state.DefaultIdempotencyStateMachine;
import com.xjtu.iron.idempotent.provider.jdbc.repository.JdbcIdempotencyRepository;
import com.xjtu.iron.transaction.api.execution.TransactionExecutor;
import com.xjtu.iron.transaction.core.executor.DefaultTransactionExecutor;
import com.xjtu.iron.transaction.provider.spring.transaction.SpringTransactionProvider;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

import javax.sql.DataSource;
import java.time.Clock;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 验证 Tx-A / Tx-B / Tx-C 事务语义。
 */
class IdempotencyTransactionIntegrationTest {

    private DataSource dataSource;
    private JdbcTemplate jdbcTemplate;
    private TransactionExecutor transactionExecutor;

    @BeforeEach
    void setUp() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:idem-tx-" + UUID.randomUUID()
                + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        this.dataSource = ds;
        this.jdbcTemplate = new JdbcTemplate(ds);

        jdbcTemplate.execute("""
                CREATE TABLE iron_idempotency_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    namespace VARCHAR(128) NOT NULL,
                    idempotency_key VARCHAR(256) NOT NULL,
                    route_key VARCHAR(256),
                    request_hash VARCHAR(128),
                    status VARCHAR(32) NOT NULL,
                    owner_token VARCHAR(128),
                    version BIGINT NOT NULL DEFAULT 0,
                    result_payload CLOB,
                    failure_code VARCHAR(128),
                    failure_message VARCHAR(1024),
                    failure_retryable BOOLEAN NOT NULL DEFAULT FALSE,
                    recovery_mode VARCHAR(32) NOT NULL DEFAULT 'NONE',
                    window_policy VARCHAR(64) NOT NULL DEFAULT 'FIXED_FROM_FIRST_ACQUIRE',
                    processing_expire_at TIMESTAMP,
                    window_expire_at TIMESTAMP,
                    retention_expire_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    completed_at TIMESTAMP,
                    CONSTRAINT uk_idem UNIQUE(namespace, idempotency_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE business_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    idempotency_key VARCHAR(256) NOT NULL,
                    payload VARCHAR(256) NOT NULL
                )
                """);

        DataSourceTransactionManager transactionManager =
                new DataSourceTransactionManager(ds);
        this.transactionExecutor = new DefaultTransactionExecutor(
                new SpringTransactionProvider(transactionManager));
    }

    @Test
    void successShouldCommitBusinessAndSuccessInSameTransaction() {
        JdbcIdempotencyRepository repository = jdbcRepository();
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("success-1"),
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "ok");
                    return "done";
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.EXECUTED);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("success-1")).isEqualTo(1);
        assertThat(repository.find("tx-test", "success-1"))
                .get()
                .extracting(IdempotencyRecord::getStatus)
                .isEqualTo(IdempotencyStatus.SUCCESS);
    }

    @Test
    void businessFailureShouldRollbackBusinessThenPersistFailedInNewTransaction() {
        JdbcIdempotencyRepository repository = jdbcRepository();
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("failure-1"),
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "must-rollback");
                    throw new IllegalStateException("boom");
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.EXECUTION_FAILED);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("failure-1")).isZero();
        assertThat(repository.find("tx-test", "failure-1"))
                .get()
                .satisfies(record -> {
                    assertThat(record.getStatus()).isEqualTo(IdempotencyStatus.FAILED);
                    assertThat(record.isFailureRetryable()).isTrue();
                });
    }

    @Test
    void completionRejectedShouldRollbackBusinessWriteInsteadOfCommittingPartialSuccess() {
        JdbcIdempotencyRepository delegate = jdbcRepository();
        IdempotencyRepository repository = new RejectingCompletionRepository(delegate);
        DefaultIdempotencyExecutor executor = executor(repository);

        IdempotencyResult<String> result = executor.execute(
                request("stale-1"),
                context -> {
                    jdbcTemplate.update(
                            "INSERT INTO business_record(idempotency_key,payload) VALUES (?,?)",
                            context.getKey(),
                            "must-rollback");
                    return "done";
                });

        assertThat(result.getStatus()).isEqualTo(IdempotencyResultStatus.OWNERSHIP_LOST);
        assertThat(result.isTransactionApplied()).isTrue();
        assertThat(countBusiness("stale-1")).isZero();
        assertThat(delegate.find("tx-test", "stale-1"))
                .get()
                .extracting(IdempotencyRecord::getStatus)
                .isEqualTo(IdempotencyStatus.PROCESSING);
    }

    private JdbcIdempotencyRepository jdbcRepository() {
        return new JdbcIdempotencyRepository(
                new SpringTransactionJdbcExecutionManager(
                        dataSource, transactionExecutor),
                "iron_idempotency_record");
    }

    private DefaultIdempotencyExecutor executor(IdempotencyRepository repository) {
        IdempotencyRepositoryRegistry repositoryRegistry =
                new DefaultIdempotencyRepositoryRegistry(
                        List.of(repository),
                        repository.providerName(),
                        repository.providerName());

        IdempotencyPolicy policy = policy();
        IdempotencyPolicyRegistry policyRegistry =
                new DefaultIdempotencyPolicyRegistry(
                        List.of(policy), policy.getName());

        return new DefaultIdempotencyExecutor(
                repositoryRegistry,
                policyRegistry,
                (namespace, key) -> UUID.randomUUID().toString(),
                (error, at) -> new IdempotencyFailureInfo(
                        "BUSINESS_ERROR",
                        error.getMessage(),
                        true,
                        at),
                null,
                new TransactionTemplateIdempotencyTransactionCoordinator(
                        transactionExecutor),
                new DefaultIdempotencyStateMachine(),
                null,
                null,
                Clock.systemUTC());
    }

    private IdempotencyRequest request(String key) {
        return IdempotencyRequest.builder()
                .key(key)
                .routeKey("merchant-1")
                .requestHash("hash-" + key)
                .policyName("tx-durable")
                .build();
    }

    private IdempotencyPolicy policy() {
        return IdempotencyPolicy.builder()
                .name("tx-durable")
                .mode(IdempotencyMode.DURABLE)
                .namespace("tx-test")
                .recoveryPolicy(IdempotencyRecoveryPolicy.externalTask())
                .build();
    }

    private int countBusiness(String key) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM business_record WHERE idempotency_key=?",
                Integer.class,
                key);
        return count == null ? 0 : count;
    }

    private static final class RejectingCompletionRepository
            implements IdempotencyRepository {

        private final JdbcIdempotencyRepository delegate;

        private RejectingCompletionRepository(
                JdbcIdempotencyRepository delegate) {
            this.delegate = delegate;
        }

        @Override
        public String providerName() {
            return "rejecting-jdbc";
        }

        @Override
        public IdempotencyRepositoryCapabilities capabilities() {
            return IdempotencyRepositoryCapabilities.builder()
                    .windowedSupported(true)
                    .durableSupported(true)
                    .resultPayloadSupported(true)
                    .businessTransactionParticipationSupported(true)
                    .recoveryQuerySupported(true)
                    .build();
        }

        @Override
        public IdempotencyAcquireResult tryAcquire(
                IdempotencyAcquireRequest request) {
            return delegate.tryAcquire(request);
        }

        @Override
        public IdempotencyRecoveryResult tryRecover(
                IdempotencyRecoveryAcquireRequest request) {
            return delegate.tryRecover(request);
        }

        @Override
        public IdempotencyWriteResult markSuccess(
                IdempotencySuccessRequest request) {
            Optional<IdempotencyRecord> current =
                    delegate.find(request.getNamespace(), request.getKey());
            return IdempotencyWriteResult.of(
                    IdempotencyWriteStatus.STALE_OWNER,
                    current.orElse(null));
        }

        @Override
        public IdempotencyWriteResult markFailed(
                IdempotencyFailureRequest request) {
            return delegate.markFailed(request);
        }

        @Override
        public Optional<IdempotencyRecord> find(
                String namespace, String key) {
            return delegate.find(namespace, key);
        }
    }
}
