server:
  port: 18081

spring:
  application:
    name: cache-demo

  data:
    redis:
      host: www.xjtu-iron.online
      port: 30379
      password: 765YSa77TA
      database: 0
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

xjtu:
  iron:
    cache:
      enabled: true

      caffeine:
        enabled: true
        default-maximum-size: 10000

      redis:
        enabled: true
        key-prefix: "cache-demo:"

      specs:
        campaignRule:
          enable-l1: true
          enable-l2: true
          ttl: 5m
          null-value-ttl: 30s
          ttl-jitter: 60s
          mutex-load: true
          null-policy: CACHE_NULL
          degrade-policy: LOAD_SOURCE
