CREATE TABLE IF NOT EXISTS iron_idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(256) NOT NULL,
    route_key VARCHAR(256),
    request_hash VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    owner_token VARCHAR(128),
    version BIGINT NOT NULL DEFAULT 0,
    result_payload CLOB,
    failure_code VARCHAR(128),
    failure_message VARCHAR(1024),
    failure_retryable BOOLEAN NOT NULL DEFAULT FALSE,
    recovery_mode VARCHAR(32) NOT NULL DEFAULT 'NONE',
    window_policy VARCHAR(64) NOT NULL DEFAULT 'FIXED_FROM_FIRST_ACQUIRE',
    processing_expire_at TIMESTAMP,
    window_expire_at TIMESTAMP,
    retention_expire_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uk_iron_idempotency_namespace_key UNIQUE(namespace, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_iron_idempotency_recovery
    ON iron_idempotency_record(recovery_mode, status, processing_expire_at, updated_at);
CREATE INDEX IF NOT EXISTS idx_iron_idempotency_route
    ON iron_idempotency_record(route_key, status, processing_expire_at);


-- 用于验证 Tx-B 的业务表：callback 写入与 iron_idempotency_record.SUCCESS 必须同事务提交/回滚。
CREATE TABLE IF NOT EXISTS demo_business_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(256) NOT NULL,
    payload VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_demo_business_idempotency_key UNIQUE(idempotency_key)
);
